name: vue-web-frame 

on: 
  push:
    branches:
      - master

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
    - uses: actions/checkout@v1
    - name: Install and Build
      run: |
        npm i
        npm start
      
