name: vue-web-frame 

on: 
  push:
    branches:
      - master

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
    - name: Install and Build
      uses: JamesIves/github-pages-deploy-action@master
      env:
        BUILD_SCRIPT: npm install && npm start
      
